const _ = require('lodash');


/* 
You have a series of digital keypads, each with 7 unique letters of the English alphabet, A-Z.

You have a list of words from the English dictionary, which are a minimum of 5 letters long, with no maximum length.

Return an array with an integer score, one score for each keypad, indicating how many of the words from the word list can be typed using the following rules:

- letters can be repeated many times within a word
- not all letters on the keypad have to be used
- each keypad is a unique list of letters (no duplicates)
- the first letter listed on the keypad MUST exist in the word

Example input:

word list:   ['APPLE', 'PLEAS', 'PLEASE']
keypad list: ['AELWXYZ', 'AELPXYZ', 'AELPSXY', 'SAELPRT', 'XAEPLSY']
Output:      [0,          1,         3,         2,         0] 

Explanation:

- 0 => all of the words contain a 'P', and the keypad does not, so 0 words could be typed
- 1 => two words contain an S, and there is no S in the keypad, so only 1 word could be typed
- 3 => all 3 words in the list could be typed on this keypad
- 2 => the first letter in the keypad, 'S', only exists in 2 of the words
- 0 => the first letter in the keypad, 'X', is not found in any of the words

We will start by testing the word list and keypads above, then try much longer combinations

kp: ['AELWXYZ', 'AELPXYZ', 'AELPSXY', 'SAELPRT', 'XAEPLSY']
   w: ['APPLE', 'PLEAS', 'PLEASE']
   



for each decision
  make decision
  repeat workd
  undo decision

 */



let wordlist = ['APPLE', 'PLEAS', 'PLEASE']
let keypads = ['AELWXYZ', 'AELPXYZ', 'AELPSXY', 'SAELPRT', 'XAEBSKY']
// output should be: [0, 1, 3, 2, 0]0

/*

   1. Preprocess our keypad
      firstLetter
      score
    2. Loop through words and compare to our keypads
        2.a Loop through each word and
          look up if we can make it
          2.ab total++
        continue
    3. Grab score from each kp and put it in output
    
    4. return output //type of array



*/
const calculateScore = (kp,words) => {
  let kps = []
  for(let i = 0;i<kp.length;i++){
    const key = {} //Keypad
    const firstLetter = kp[i][0]
    key.firstLetter = firstLetter
    key.score = 0
    const code = kp[i]
    for(let j = 0;j<code.length;j++){
          key[code[j]] = true
    }
    kps.push(key)
  }
  
  for(let w = 0;w<words.length;w++){
    const word = words[w]
    
      for(let k = 0;k<kps.length;k++){
        const hash = kps[k]
        let notFound = false
        let exist = false
        for(let char in word){
          if(word[char] === hash.firstLetter){
           exist = true 
          }
          if(word[char] in hash === false){
           notFound = true 
          }
        }
        if(notFound === false && exist === true){
          kps[k].score = kps[k].score + 1
        }
      }
  }
  
  let output = []
  for(let i = 0;i<kps.length;i++){
   output.push(kps[i].score)
  }
  //4.
 return output
}

// console.log(calculateScore(keypads,wordlist))




wordlist = ["ANTITRINITARIAN", "NONTRINITARIAN", "ANTIATTRITION", "REORIENTATION", "ANTIROTATION", "ETERNITARIAN", "INANITIATION", "INTENERATION", "NANOANTENNAE", "NATROTANTITE", "NONATITANATE", "NONATTENTION", "NONITINERANT", "NONREENTRANT", "NORNANTENINE", "REANNOTATION", "REINITIATION", "TATTARRATTAT", "TEETERTOTTER", "TETRANITRATE", "TETRATAENITE", "TITTERTOTTER", "ANTENNATION", "ANTONINIANI", "ARRENTATION", "ATTERRATION", "ENTERTAINER", "ENTERTAININ", "INATTENTION", "INTENTATION", "INTERNATION", "INTERNETTER", "IRRETENTION", "ITINERATION", "NANOANTENNA", "NANOTITANIA", "NANTERINONE", "NITRATATION", "NONANTERIOR", "NONINITIATE", "NONIRRITANT", "NONROTATION", "ORIENTATION", "ORIENTEERER", "REITERATION", "RENARRATION", "REORIENTATE", "RIOTINTOITE", "TARATANTARA", "TERRETENANT", "TERRITORIAN", "TETRAONINAE", "TITTERATION", "TORONTARIAN", "TORONTONIAN", "TRATTNERITE", "TRINITARIAN", "AAROOAAROO", "AETERNITIE", "ANNOTATION", "ANNOTINATA", "ANNOTININE", "ANTIRENTER", "ANTITATTOO", "ANTITERROR", "ANTITRITON", "ANTOINETTE", "ARIETATION", "ENARRATION", "ENTERTAINE", "ETRETINATE", "INERTINITE", "INITIATION", "INTENERATE", "INTERANION", "INTERRATER", "INTERTRAIN", "INTONATION", "INTRARATER", "IRANIANATE", "IRRITATION", "IRRORATION", "ITINERARIA", "NANOTAINER", "NINEONEONE", "NITROANION", "NITROARENE", "NONATRIENE", "NONTOTIENT", "NONTRONITE", "ONORATOITE", "ORIENTATOR", "RATATATTAT", "REAERATION", "REANNOTATE", "REINITIATE", "REITERATOR", "RETREATANT", "ROTATORIAN", "TAONIANONE", "TARTRONATE", "TENNANTITE", "TENORITONE", "TERRARANAN", "TETRAANION", "TETRANITRO", "TINTINAITE", "TITANATION", "TORRENTINE", "TRENTONIAN", "TRINITRATE", "TRITERNATE", "TRITIATION", "AENIANIAN", "AERIATION", "AEROTRAIN", "ANNOTATER", "ANNOTATOR", "ANTENNATE", "ANTIENTER", "ANTINOANA", "ANTINORII", "ANTIRENIN", "ANTIRRION", "ANTITRAIN", "ANTONETTI", "AOTEAROAN", "ARENATION", "ARIANATOR", "ARTERNOON", "ARTROEITE", "ATRANORIN", "ATTENTATE", "ATTENTION", "ATTERRATE", "ATTRITION", "ENNIANTIN", "ENNIATINE", "ENTENTION", "ENTERTAIN", "ENTRAINER", "ENTREATER", "INANITION", "INITIATOR", "INTENTION", "INTERAREA", "INTERIANO", "INTERTONE", "INTERTREE", "INTONATOR", "INTORTION", "INTRANATO", "IRRITATOR", "ITERATION", "ITINERANT", "ITINERATE", "ITTNERITE", "NANTENINE", "NARRATION", "NATATORIA", "NATTERIER", "NEOATTINE", "NEOTEINIA", "NITRATIAN", "NITRATINE", "NITRATION", "NITRATITE", "NITRONATE", "NONANOATE", "NONEARNER", "NONRENNET", "NONRIOTER", "NONTENANT", "NONTERROR", "NOTIONATE", "ONERATION", "ORATORIAN", "ORIENTATE", "ORIENTEER", "ORIENTITE", "RATTATTAT", "RATTERREE", "REENTRANT", "REINERITE", "REITERANT", "REITERATE", "RENARRATE", "RENIERITE", "RENOIRIAN", "RERETREAT", "RETENTATE", "RETENTION", "RETINOATE", "RETORTION", "RETRAINEE", "RETRAINER", "RETREATER", "RETROTORT", "RINTINTIN", "TANTARARA", "TARANTARA", "TARANTIAN", "TARANTINI", "TARANTINO", "TARENTINE", "TARNATION", "TARTAREAN", "TARTARIAN", "TARTARINE", "TARTINIAN", "TATTARARA", "TATTERARA", "TATTERIER", "TENTATION", "TERENTIAN", "TERRANEAN", "TERRIANNE", "TERTENANT", "TETEATETE", "TETRAIRON", "TETRATION", "TETRONATE", "TIETTAITE", "TINTERNET", "TITRATION", "TONTINEER", "TONTINIER", "TORNARIAE", "TORRENTER", "TORTONIAN", "TOTTERIER", "TRANATION", "TRATTORIA", "TRATTORIE", "TRETINOIN", "TRIENTINE", "TRINATION", "TRINITITE", "TRINITRIN", "TRITONIAN", "TROTTOIRE", "AARONITE", "AENIANIA", "AERARIAN", "AERATION", "AERINITE", "AERONIAN", "AEROTONE", "AIRTOAIR", "ANATINAE", "ANIONITE", "ANNOTATE", "ANOINTEE", "ANOINTER", "ANTAREAN", "ANTARIAN", "ANTEATER", "ANTENATI", "ANTENNAE", "ANTERIOR", "ANTERNET", "ANTIARIN", "ANTINOAN", "ANTIRENT", "ANTIRION", "ANTIRIOT", "ANTIRRIO", "ANTONINA", "ANTONINE", "AOTEAROA", "AOTEROAN", "ARANOTIN", "ARENARIA", "ARIETIAN", "ARIETINE", "ARRANTER", "ARRARNTA", "ARRERNTE", "ARRETINE", "ARTERATI", "ARTERIAE", "ARTINIAN", "ARTINITE", "ATTAINER", "ATTAINOR", "ATTENTAT", "ATTERTON", "ATTRITEE", "ATTRITER", "ATTRITOR", "ENANTATE", "ENNIATIN", "ENTERATE", "ERETRIAN", "ERIONITE", "ERITORAN", "ERITREAN", "ERRATION", "IANNOTTI", "INERRANT", "INERTIAE", "INERTION", "INITIATE", "INNERNET", "INORNATE", "INTERION", "INTERIOR", "INTERNEE", "INTERNET", "INTERRER", "INTERTIE", "INTONATE", "INTORTOR", "INTRANET", "IOANNINA", "IOTATION", "IRENAEAN", "IRRITANT", "IRRITATE", "IRRORATE", "ITERATOR", "NANOTORI", "NANTERRE", "NARRATEE", "NARRATER", "NARRATOR", "NATANITE", "NATATION", "NATTERER", "NEOTENIA", "NEOTENIN", "NERITINA", "NERONIAN", "NETINETI", "NINETEEN", "NITRATOR", "NONANONE", "NONERROR", "NONINERT", "NONTRAIN", "NORANIAN", "NORINONE", "NOTATION", "NOTITIAE", "OENOTRIA", "ONEONONE", "ONETOONE", "ONIONIER", "ONTARIAN", "ORATORIO", "ORIENATE", "ORIENTEE", "ORIENTER", "ORIENTIA", "ORIENTIN", "ORNERIER", "ORONTEAN", "ORONTIAN", "ORRANTIA", "ORTONIAN", "OTARIINE", "OTTONIAN", "RAATRANI", "RAINTREE", "RANARIAN", "RATIONER", "RATITATE", "RATOONER", "RATTENER", "RATTINET", "RATTONER", "REAERATE", "REANOINT", "REATTAIN", "REINETTE", "REINTERN", "RENITENT", "RENTERER", "RENTERIA", "REORIENT", "REROTATE", "RETAINER", "RETATTOO", "RETENTOR", "RETIARII", "RETINENE", "RETINITE", "RETIRANT", "RETORTER", "RETRAITE", "RETRAITT", "RINNEITE", "RIRORIRO", "RITRATTO", "RORATION", "ROTARIAN", "ROTATION", "ROTENONE", "ROTTENER", "TAENIATE", "TARTRATE", "TATARARA", "TATARIAN", "TATTOOEE", "TATTOOER", "TEENTIER", "TEETERER", "TEINEITE", "TENIENTE", "TENINONE", "TENONIAN", "TENORINI", "TENORINO", "TENORITE", "TENOROON", "TENTORIA", "TENTORII", "TERATORN", "TERRARIA", "TERTIATE", "TETRAENE", "TINNIENT", "TIRONIAN", "TITANATE", "TITANEAN", "TITANIAN", "TITANITE", "TITANOAN", "TITONIAN", "TITRATOR", "TITTATTO", "TITTERER", "TOETOTOE", "TONATION", "TONTINER", "TORATORA", "TORNARIA", "TOTTERER", "TRENETTE", "TRENTINI", "TRENTINO", "TRIANION", "TRIARIAN", "TRIENNIA", "TRINITRO", "TRITIATE", "TRITONIA", "TRITORIA", "TRONATOR", "TROTTIER", "TROTTOIR", "AEONIAN", "AERATOR", "AERENIA", "AERIATE", "AERONAT", "AINTREE", "ANATINE", "ANATION", "ANATRON", "ANNATTA", "ANNATTO", "ANNETTE", "ANNOINT", "ANNONIN", "ANNOTTO", "ANTAEAN", "ANTENNA", "ANTENOR", "ANTIAIR", "ANTIART", "ANTIENT", "ANTIRAT", "ANTITEA", "ANTOINE", "ANTONIA", "ANTONIO", "ARANEAE", "ARATION", "ARENITE", "ARIANNA", "ARIANNE", "ARIETTA", "ARIETTE", "ARNATTO", "ARNETTE", "ARNOTTA", "ARNOTTO", "AROANIA", "AROEIRA", "ARRENTE", "ARRIERE", "ARRIERO", "ARRIETA", "ARTERIA", "ATARIAN", "ATERIAN", "ATOTTER", "ATTAINT", "ATTEINT", "ATTIRER", "ATTRITE", "EATERIE", "EATONIA", "ENATION", "ENTENTE", "ENTERER", "ENTERON", "ENTETEE", "ENTRAIN", "ENTRANT", "ENTREAT", "ERETRIA", "ERINITE", "ERITREA", "ETAERIO", "ETONIAN", "ETRENNE", "IANNONE", "IIITIAN", "INERTER", "INERTIA", "INITION", "INORITE", "INTERNE", "INTONER", "INTRANT", "INTRATA", "INTREAT", "INTROIT", "IRANIAN", "IRANITE", "IRATION", "IRIARTE", "IRONIER", "IRONTON", "ITERANT", "ITERATE", "NANOART", "NANONET", "NANORNA", "NARNIAN", "NARRATE", "NATATOR", "NATRIAN", "NATRITE", "NATRONA", "NATTIER", "NEONATE", "NEONOIR", "NETROOT", "NETTIER", "NIERITE", "NINIANE", "NITERIE", "NITRATE", "NITRENE", "NITRIAN", "NITRITE", "NITRONE", "NITTIER", "NOETIAN", "NOINTER", "NONETTE", "NONETTI", "NONETTO", "NONIRON", "NONRARE", "NONROOT", "NONTORT", "NONTREE", "NOORANI", "NORETTE", "NORTENA", "NORTENO", "NOTAIRE", "NOTARIA", "NOTATIN", "NOTATOR", "NOTITIA", "ONEIROI", "ONENOTE", "ONEONTA", "ONERATE", "ONERIER", "ONTARIO", "ONTRAIN", "ORANIAN", "ORARIAN", "ORARION", "ORATION", "ORNATER", "OROTATE", "OROTONE", "ORRORIN", "OTARINE", "OTATARA", "RAINIER", "RAINONE", "RANIERI", "RANTIER", "RARITIE", "RATATAT", "RATETTE", "RATITAE", "RATTEEN", "RATTIER", "RATTOON", "REENTER", "REENTRE", "REINERT", "REINTER", "REITANO", "RENETTE", "RENTIER", "RETARIA", "RETIARI", "RETINAE", "RETINEA", "RETIREE", "RETIRER", "RETRAIN", "RETRAIT", "RETRATE", "RETREAT", "ROARIER", "ROOTIER", "ROOTROT", "RORTIER", "ROTATOR", "TAENIAE", "TAENITE", "TAINTER", "TAIRONA", "TAITANO", "TANAINA", "TANNATE", "TANNERI", "TANNIER", "TANTARA", "TANTITE", "TARAIRE", "TARANTO", "TARATOR", "TARRANT", "TARRIER", "TARTANA", "TARTANE", "TARTARE", "TARTIER", "TARTINE", "TATIANA", "TATTIER", "TEARIER", "TEENIER", "TENNANT", "TENNETI", "TENONER", "TENORIO", "TENTIER", "TERATON", "TERNATE", "TERNION", "TERRAIN", "TERRANE", "TERREEN", "TERRENE", "TERRERO", "TERRIEN", "TERRIER", "TERRINE", "TERROIR", "TERTIAN", "TETANIN", "TETRONE", "TIERNAN", "TINEINA", "TINNIER", "TINTIER", "TIRANAN", "TITANIA", "TITRANT", "TITRATE", "TONETTE", "TONTINE", "TORNOTE", "TORONTO", "TORRENT", "TORRERT", "TORRION", "TORTION", "TORTONI", "TORTORA", "TOTIENT", "TOTTARI", "TOTTIER", "TOTTORI", "TRAINEE", "TRAINER", "TRAININ", "TRAINOR", "TRAITOR", "TRANENT", "TRANNIE", "TRANTER", "TREANOR", "TREATER", "TREETON", "TRENTIN", "TRENTON", "TRETTER", "TRIANON", "TRIARII", "TRITONE", "TRITTON", "TROIANO", "TROTTER", "TROTTIN", "AEAEAN", "AEANNA", "AERATE", "AERIAN", "AERIER", "AETTIR", "AIRIER", "ANANTA", "ANATTA", "ANATTO", "ANITTA", "ANNATE", "ANNETT", "ANNITE", "ANNONA", "ANOINT", "ANOTIA", "ANOTTA", "ANTARA", "ANTIAE", "ANTIAN", "ANTIAR", "ANTONE", "ANTRIN", "AONIAN", "AORTAE", "ARAARA", "ARARAT", "AREARE", "AREITO", "ARENAE", "ARIANA", "ARIANE", "ARNAIA", "ARNETT", "ARNONE", "ARNOTT", "AROENA", "AROINT", "ARONIA", "ARRANT", "ARREAR", "ARRIET", "ARTIER", "ARTINA", "ATAATA", "ATONER", "ATONIA", "ATRANE", "ATRATE", "ATRINE", "ATTAIN", "ATTENT", "ATTERN", "ATTINE", "ATTINI", "ATTIRE", "ATTONE", "ATTORN", "ATTRIT", "EARNER", "EARNIN", "EERIER", "EIRENE", "EIRINI", "ENOATE", "ENROOT", "ENTENT", "ENTERA", "ENTETE", "ENTIER", "ENTIRE", "ENTREE", "EONIAN", "ERRANT", "ERRATA", "ETERNE", "ETNEAN", "ETRIER", "IITIAN", "INANER", "INANNA", "INNATE", "INTEIN", "INTENT", "INTERN", "INTINE", "INTIRE", "INTONE", "INTORT", "INTREE", "INTRON", "IONENE", "IONIAN", "IONONE", "IRANIA", "IRATER", "IRETON", "IRONER", "IRONIA", "ITERON", "ITOITE", "ITTIER", "ITTRIA", "NAENIA", "NAIANT", "NANITE", "NANNAN", "NANNER", "NANNIE", "NANORI", "NANTEE", "NANTEN", "NANTON", "NARAIN", "NARINE", "NARITA", "NARNER", "NARNIA", "NARRON", "NATANT", "NATERA", "NATION", "NATORI", "NATRON", "NATTER", "NATTIE", "NATTON", "NEAERA", "NEARER", "NEATEN", "NEATER", "NEENER", "NEINEI", "NERINE", "NERION", "NERITA", "NERITE", "NETNET", "NETRIN", "NETTER", "NETTIE", "NIENTE", "NINEIN", "NITTER", "NITTIE", "NONAIR", "NONANE", "NONART", "NONENE", "NONION", "NONNIE", "NONRAT", "NONTIN", "NOONAN", "NOONER", "NOONIE", "NOREEN", "NORIAN", "NORITE", "NORRIE", "NORRIN", "NORTIA", "NORTON", "NOTAEA", "NOTARO", "NOTATE", "NOTION", "NOTNOT", "NRITTA", "OARIER", "OATIER", "OENITE", "OENONE", "OETAEA", "ONONIN", "OORARI", "OORIER", "ORANIA", "ORARIA", "ORATOR", "ORIENT", "ORNATE", "ORNEAE", "OTRERA", "OTTOIA", "RAETIA", "RAINER", "RAININ", "RANINE", "RANTER", "RAROIA", "RATEEN", "RATINE", "RATION", "RATITE", "RATNER", "RATOON", "RATTAN", "RATTEN", "RATTER", "RATTON", "REANNE", "REARER", "REEARN", "REENIE", "REITER", "RENATA", "RENATE", "RENNET", "RENNIE", "RENNIN", "RENOIR", "RENTEE", "RENTER", "RENTON", "RENTOR", "RERATE", "RERENT", "REROOT", "RETAIN", "RETANA", "RETEAR", "RETENE", "RETENT", "RETIER", "RETINA", "RETINE", "RETINT", "RETIRE", "RETONE", "RETORE", "RETORN", "RETORT", "RETREE", "RETRON", "RETTER", "RINEER", "RIOTER", "RITTEN", "RITTER", "ROARER", "ROARIE", "ROARIN", "RONEAT", "RONION", "RONNIE", "ROOTER", "ROOTIN", "RORIER", "RORRER", "RORTER", "ROTANE", "ROTATE", "ROTINI", "ROTTAN", "ROTTEN", "ROTTER", "ROTTIE", "ROTTIN", "TAENIA", "TAINAN", "TANANA", "TANIER", "TANITE", "TANNAN", "TANNER", "TANNIA", "TANNIE", "TANNIN", "TANOAN", "TANTON", "TANTRA", "TAOTAI", "TAOTIE", "TAREEN", "TARTAN", "TARTAR", "TARTEN", "TARTER", "TATANE", "TATARA"]
keypads = ["EARTION", "NEARTIO", "ONEARTI",
           "INEARTO", "TNEARIO", "RTNEAIO", "ANETRIO"]
// output should be: [703, 817, 506, 682, 862, 770, 720]
console.log(calculateScore(keypads,wordlist))
